CREATE USER mmdb_user IDENTIFIED BY Mmdb#2026
  DEFAULT TABLESPACE users
  TEMPORARY TABLESPACE temp
  QUOTA UNLIMITED ON users;

GRANT CREATE SESSION TO mmdb_user;
GRANT CREATE TABLE TO mmdb_user;
GRANT CREATE VIEW TO mmdb_user;
GRANT CREATE SEQUENCE TO mmdb_user;
GRANT CREATE PROCEDURE TO mmdb_user;
GRANT CREATE TRIGGER TO mmdb_user;
GRANT CREATE TYPE TO mmdb_user;